service: catalog-categories

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/CategoriesTable"

functions:
  addCategory:
    handler: dist/handlers/addCategory.handler
    events:
      - http:
          path: categories
          method: put
          cors: true
  listCategories:
    handler: dist/handlers/listCategories.handler
    events:
      - http:
          path: categories
          method: get
          cors: true
  updateCategory:
    handler: dist/handlers/updateCategory.handler
    events:
      - http:
          path: categories/{id}
          method: post
          cors: true
  deleteCategory:
    handler: dist/handlers/deleteCategory.handler
    events:
      - http:
          path: categories/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline
  - serverless-dynamodb-local

resources:
  Resources:
    CategoriesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: CategoriesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8001
      inMemory: true
      migrate: true
